# This manifest defines a Service to expose the NGINX Deployment
apiVersion: v1  # API version for Service resources
kind: Service   # Indicates that this resource is a Service
metadata:
  name: nginx-service  # The name of the Service
spec:
  selector:
    app: nginx  # Selects Pods with this label to route traffic to
  ports:
    - protocol: TCP  # Protocol used by the Service
      port: 80       # Port exposed by the Service
      targetPort: 80 # Port on the Pod that traffic will be forwarded to
  type: ClusterIP    # Type of Service (ClusterIP is internal to the cluster)
